doctrine:
    dbal:
        dbname:               '%env(DB_NAME)%'
        host:                 '%env(DB_HOST)%'
        port:                 3306
        user:                 '%env(DB_USER)%'
        password:             '%env(DB_PASS)%'
        driver:               pdo_mysql
        # if the url option is specified, it will override the above config
        # url:                  mysql://db_user:db_password@127.0.0.1:3306/db_name
        # the DBAL driverClass option
        # driver_class:         App\DBAL\MyDatabaseDriver
        # the DBAL driverOptions option
        # options:
            # foo: bar
        # path:                 '%kernel.project_dir%/var/data/data.sqlite'
        memory:               true
        # unix_socket:          /tmp/mysql.sock
        # the DBAL wrapperClass option
        # wrapper_class:        App\DBAL\MyConnectionWrapper
        charset:              utf8mb4
        # logging:              '%kernel.debug%'
        # platform_service:     App\DBAL\MyDatabasePlatformService
        server_version:       '8.0.31'
        # mapping_types:
            # enum: string
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'


when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
